[package]
name = "loc_share"
version = "0.1.1"
authors = ["Lukasz Barcinski <lukasz.barcinski@enigma.com.pl>"]
edition = "2018"


[dependencies]
openssl-sys = "0.9"
openssl = "0.10.73"
hex = "0.4.2"
rand = "0.8.1"
protobuf = "3.7.2"
dirs = "6.0.0"

[build-dependencies]
protobuf-codegen = "3.7.2"
