[package]
name = "loc_share"
version = "0.1.1"
authors = ["Lukasz Barcinski <lukasz.barcinski@enigma.com.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
